// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// monoSmooth
NumericVector monoSmooth(NumericVector pvalue, NumericVector z, NumericVector lfdr, double window);
RcppExport SEXP fFDR_monoSmooth(SEXP pvalueSEXP, SEXP zSEXP, SEXP lfdrSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type pvalue(pvalueSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lfdr(lfdrSEXP );
        Rcpp::traits::input_parameter< double >::type window(windowSEXP );
        NumericVector __result = monoSmooth(pvalue, z, lfdr, window);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
