// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// monoSmooth
NumericVector monoSmooth(NumericVector pvalue, NumericVector z, NumericVector density, double window);
RcppExport SEXP fFDR_monoSmooth(SEXP pvalueSEXP, SEXP zSEXP, SEXP densitySEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pvalue(pvalueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type density(densitySEXP);
    Rcpp::traits::input_parameter< double >::type window(windowSEXP);
    __result = Rcpp::wrap(monoSmooth(pvalue, z, density, window));
    return __result;
END_RCPP
}
